name: run-gatling
  # description: Runs a Gatling test suite
on:
  workflow_call:
    inputs:
      javaVersion:
        description: "Java version to use"
        default: "11.0.19"
        type: string
      javaDistribution:
        description: "Java distribution to use"
        default: "microsoft"
        type: string
      simulationClass:
        description: "The fully qualified name of the simulation to run (e.g. com.proxibid.MySimulation)"
        required: true
        type: string
      service_url:
        description: "The http service to run against"
        required: true
        type: string
jobs:
  load_tests:
    runs-on: stage-arc-runner-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Execute Gatling Test Suite      
        uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.javaDistribution }}
          java-version: ${{ inputs.javaVersion }}

      - run: chmod +x ./gradlew && ./gradlew gatlingRun-${{inputs.simulationClass}}
        shell: bash
        env:
          BASE_URL: ${{ inputs.service_url }}
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: gatling-reports
          path: build/reports/gatling/smoketest-*/**/*
          retention-days: 180
      